/**
 * VIDYA STEM – Tinkering Lab Inventory System
 * Export Module  |  js/export.js
 *
 * Supports two formats for BOTH Bulk and Individual audits:
 *   1. Excel (.csv) – comma-separated, opens directly in Microsoft Excel
 *   2. Image (.png) – canvas-rendered audit report card
 *
 * Usage:
 *   exporter.showModal(auditRecord, labMeta)
 */

const exporter = {

  /** Entry point – show format choice modal */
  showModal: function (auditRecord, labMeta) {
    this._removeModal();
    const overlay = document.createElement('div');
    overlay.id = 'export-overlay';
    overlay.innerHTML = `
      <div class="export-modal glass-card">
        <div class="export-modal-header">
          <i class="fa-solid fa-file-export"></i>
          <h3>Download Audit Report</h3>
          <p>Choose your preferred format</p>
        </div>
        <div class="export-options">
          <button class="export-btn export-excel" id="exp-excel-btn">
            <div class="exp-icon"><i class="fa-solid fa-file-excel"></i></div>
            <div class="exp-label">
              <strong>Excel Format</strong>
              <span>Spreadsheet (.csv)</span>
            </div>
          </button>
          <button class="export-btn export-image" id="exp-image-btn">
            <div class="exp-icon"><i class="fa-solid fa-image"></i></div>
            <div class="exp-label">
              <strong>Image Format</strong>
              <span>Report card (.png)</span>
            </div>
          </button>
        </div>
        <button class="export-skip" id="exp-skip-btn">Skip – Go to Dashboard</button>
      </div>
    `;

    document.getElementById('app').appendChild(overlay);

    document.getElementById('exp-excel-btn').onclick = () => {
      this.toExcel(auditRecord, labMeta);
      this._removeModal();
      app.showDashboard();
    };
    document.getElementById('exp-image-btn').onclick = async () => {
      this._removeModal();
      await this.toImage(auditRecord, labMeta);
      app.showDashboard();
    };
    document.getElementById('exp-skip-btn').onclick = () => {
      this._removeModal();
      app.showDashboard();
    };
  },

  _removeModal: function () {
    const old = document.getElementById('export-overlay');
    if (old) old.remove();
  },

  /* ─────────────────────────────────────────
     EXCEL / CSV EXPORT
  ───────────────────────────────────────── */
  toExcel: function (rec, labMeta) {
    const BOM   = '\uFEFF'; // UTF-8 BOM for Excel
    const lines = [];

    lines.push(`"${LABS_DATA.config.orgName} – ${LABS_DATA.config.labName}"`);
    lines.push(`"Audit Report – ${labMeta.name}"`);
    lines.push(`"Date:","${rec.date}"`);
    lines.push(`"Audited By:","${rec.user}"`);
    lines.push(`"Entry Type:","${rec.entryType}"`);
    lines.push('');

    // Summary block
    lines.push('"── SUMMARY ──"');
    lines.push('"Well Present","Broken","Missing"');
    lines.push(`${rec.summary.well},${rec.summary.broken},${rec.summary.missing}`);
    lines.push('');

    // Item detail block
    lines.push('"── ITEM DETAILS ──"');
    if (rec.entryType === 'Individual') {
      lines.push('"#","Item Name","Category","Expected Qty","Status"');
      rec.details.forEach((d, i) => {
        lines.push(`${i + 1},"${d.item}","${d.category}",${d.expected},"${d.status}"`);
      });
    } else {
      lines.push('"#","Item Name","Category","Expected Qty","Counted Qty","Broken","Missing"');
      rec.details.forEach((d, i) => {
        lines.push(`${i + 1},"${d.item}","${d.category}",${d.expected},${d.present},${d.broken},${d.missing}`);
      });
    }

    lines.push('');
    lines.push(`"Generated by ${LABS_DATA.config.orgName} Inventory System v${LABS_DATA.config.version}"`);

    const csv  = BOM + lines.join('\r\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url  = URL.createObjectURL(blob);
    const ts   = new Date().toISOString().slice(0, 10);
    this._triggerDownload(url, `audit_${rec.labId}_${ts}.csv`);
    URL.revokeObjectURL(url);
  },

  /* ─────────────────────────────────────────
     IMAGE / PNG EXPORT  (Canvas-based)
  ───────────────────────────────────────── */
  toImage: function (rec, labMeta) {
    return new Promise((resolve) => {
      const canvas  = document.createElement('canvas');
      const W       = 520;
      const itemH   = 30;
      const itemsToShow = rec.details.slice(0, 20); // cap at 20 rows
      const totalH  = 520 + (itemsToShow.length * itemH);
      canvas.width  = W;
      canvas.height = totalH;
      const ctx = canvas.getContext('2d');

      // Background
      ctx.fillStyle = '#0f172a';
      ctx.fillRect(0, 0, W, totalH);

      // Gradient header strip
      const grad = ctx.createLinearGradient(0, 0, W, 80);
      grad.addColorStop(0, '#1e3a5f');
      grad.addColorStop(1, '#1e1b4b');
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, W, 80);

      // Helper: rounded rect
      const rr = (x, y, w, h, r, fill) => {
        ctx.beginPath();
        ctx.moveTo(x + r, y);
        ctx.lineTo(x + w - r, y);
        ctx.quadraticCurveTo(x + w, y, x + w, y + r);
        ctx.lineTo(x + w, y + h - r);
        ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
        ctx.lineTo(x + r, y + h);
        ctx.quadraticCurveTo(x, y + h, x, y + h - r);
        ctx.lineTo(x, y + r);
        ctx.quadraticCurveTo(x, y, x + r, y);
        ctx.closePath();
        ctx.fillStyle = fill;
        ctx.fill();
      };

      // Org name
      ctx.fillStyle = '#60a5fa';
      ctx.font = 'bold 13px Arial';
      ctx.fillText(LABS_DATA.config.orgName.toUpperCase(), 24, 28);

      // Lab name
      ctx.fillStyle = '#f8fafc';
      ctx.font = 'bold 20px Arial';
      ctx.fillText(labMeta.name, 24, 55);

      // Audit Report subtitle
      ctx.fillStyle = '#94a3b8';
      ctx.font = '12px Arial';
      ctx.fillText('INVENTORY AUDIT REPORT', 24, 74);

      let y = 105;

      // Info block
      rr(20, y, W - 40, 95, 10, 'rgba(30,41,59,0.9)');
      const infoPairs = [
        ['Date & Time', rec.date],
        ['Audited By',  rec.user],
        ['Entry Type',  rec.entryType]
      ];
      infoPairs.forEach((pair, i) => {
        const ry = y + 18 + i * 28;
        ctx.fillStyle = '#64748b';
        ctx.font = '11px Arial';
        ctx.fillText(pair[0], 38, ry);
        ctx.fillStyle = '#f8fafc';
        ctx.font = 'bold 12px Arial';
        ctx.fillText(pair[1], 38 + 120, ry);
      });
      y += 115;

      // Summary boxes
      const statBoxW = (W - 60) / 3;
      const stats = [
        { label: 'Well Present', val: rec.summary.well,    bg: 'rgba(16,185,129,0.15)',  border: 'rgba(16,185,129,0.4)',  color: '#10b981' },
        { label: 'Broken',       val: rec.summary.broken,  bg: 'rgba(245,158,11,0.15)', border: 'rgba(245,158,11,0.4)',  color: '#f59e0b' },
        { label: 'Missing',      val: rec.summary.missing, bg: 'rgba(239,68,68,0.15)',  border: 'rgba(239,68,68,0.4)',   color: '#ef4444' }
      ];
      stats.forEach((s, i) => {
        const bx = 20 + i * (statBoxW + 10);
        rr(bx, y, statBoxW, 65, 10, s.bg);
        ctx.strokeStyle = s.border;
        ctx.lineWidth   = 1;
        ctx.stroke();
        ctx.fillStyle = s.color;
        ctx.font      = 'bold 28px Arial';
        ctx.textAlign = 'center';
        ctx.fillText(s.val, bx + statBoxW / 2, y + 36);
        ctx.fillStyle = '#94a3b8';
        ctx.font      = '10px Arial';
        ctx.fillText(s.label, bx + statBoxW / 2, y + 54);
        ctx.textAlign = 'left';
      });
      y += 85;

      // Items section
      if (itemsToShow.length > 0) {
        ctx.fillStyle = '#64748b';
        ctx.font      = '10px Arial';
        ctx.fillText('ITEM DETAILS', 24, y);
        y += 12;

        itemsToShow.forEach((d, i) => {
          const rowBg = i % 2 === 0 ? 'rgba(30,41,59,0.8)' : 'rgba(15,23,42,0.6)';
          rr(20, y, W - 40, 24, 4, rowBg);

          ctx.fillStyle = '#e2e8f0';
          ctx.font      = '11px Arial';
          ctx.fillText(d.item.substring(0, 30), 34, y + 16);

          // Status / qty
          let statusText, statusColor;
          if (rec.entryType === 'Individual') {
            statusText  = d.status;
            statusColor = d.status === 'Well Present' ? '#10b981' : d.status === 'Broken' ? '#f59e0b' : '#ef4444';
          } else {
            const issues = [];
            if (d.broken  > 0) issues.push(`${d.broken} Broken`);
            if (d.missing > 0) issues.push(`${d.missing} Missing`);
            statusText  = issues.length ? issues.join(', ') : `${d.present} OK`;
            statusColor = issues.length ? '#f59e0b' : '#10b981';
          }
          ctx.fillStyle  = statusColor;
          ctx.font       = 'bold 11px Arial';
          ctx.textAlign  = 'right';
          ctx.fillText(statusText, W - 30, y + 16);
          ctx.textAlign  = 'left';

          y += itemH;
        });
      } else {
        rr(20, y, W - 40, 44, 10, 'rgba(16,185,129,0.1)');
        ctx.fillStyle = '#10b981';
        ctx.font      = 'bold 14px Arial';
        ctx.textAlign = 'center';
        ctx.fillText('✓  All items accounted for', W / 2, y + 28);
        ctx.textAlign = 'left';
        y += 64;
      }

      // Footer
      y += 16;
      ctx.fillStyle = '#334155';
      ctx.fillRect(20, y, W - 40, 1);
      y += 16;
      ctx.fillStyle = '#475569';
      ctx.font      = '10px Arial';
      ctx.textAlign = 'center';
      ctx.fillText(`${LABS_DATA.config.orgName} Inventory System v${LABS_DATA.config.version}`, W / 2, y);

      // Download
      const url = canvas.toDataURL('image/png');
      const ts  = new Date().toISOString().slice(0, 10);
      this._triggerDownload(url, `audit_${rec.labId}_${ts}.png`);
      resolve();
    });
  },

  /* ─────────────────────────────────────────
     HISTORY EXPORT  (by user, full range)
  ───────────────────────────────────────── */
  historyToExcel: function (username, audits) {
    if (!audits.length) { alert(`No audit records found for "${username}".`); return; }
    const BOM   = '\uFEFF';
    const lines = [];
    lines.push(`"${LABS_DATA.config.orgName} – Audit Work History"`);
    lines.push(`"Staff:","${username}"`);
    lines.push(`"Exported:","${new Date().toLocaleString()}"`);
    lines.push('');
    lines.push('"Date","Lab","Entry Type","Well","Broken","Missing","Issues"');
    audits.forEach(a => {
      const issues = (a.details || [])
        .filter(d => {
          if (a.entryType === 'Individual') return d.status !== 'Well Present';
          return d.broken > 0 || d.missing > 0;
        })
        .map(d => a.entryType === 'Individual' ? `${d.item}: ${d.status}` : `${d.item}: B${d.broken}/M${d.missing}`)
        .join(' | ');
      lines.push(`"${a.date}","${a.labName}","${a.entryType}",${a.summary.well},${a.summary.broken},${a.summary.missing},"${issues}"`);
    });
    const csv  = BOM + lines.join('\r\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url  = URL.createObjectURL(blob);
    this._triggerDownload(url, `history_${username}_${new Date().toISOString().slice(0,10)}.csv`);
    URL.revokeObjectURL(url);
  },

  historyToImage: function (username, audits) {
    return new Promise((resolve) => {
      if (!audits.length) { alert(`No audit records for "${username}".`); resolve(); return; }

      const canvas = document.createElement('canvas');
      const W      = 520;
      const rowH   = 38;
      const rows   = audits.slice(0, 25);
      canvas.width  = W;
      canvas.height = 160 + rows.length * rowH + 60;
      const ctx    = canvas.getContext('2d');

      ctx.fillStyle = '#0f172a';
      ctx.fillRect(0, 0, W, canvas.height);

      const grad = ctx.createLinearGradient(0, 0, W, 80);
      grad.addColorStop(0, '#1e3a5f');
      grad.addColorStop(1, '#1e1b4b');
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, W, 80);

      ctx.fillStyle = '#60a5fa';
      ctx.font      = 'bold 13px Arial';
      ctx.fillText(LABS_DATA.config.orgName.toUpperCase(), 24, 28);

      ctx.fillStyle = '#f8fafc';
      ctx.font      = 'bold 20px Arial';
      ctx.fillText(`Work History — ${username}`, 24, 55);

      ctx.fillStyle = '#94a3b8';
      ctx.font      = '11px Arial';
      ctx.fillText(`Exported: ${new Date().toLocaleString()}`, 24, 74);

      let y = 105;
      // Column headers
      ctx.fillStyle = '#475569';
      ctx.font      = '10px Arial';
      ['DATE', 'LAB', 'TYPE', 'OK', 'BRK', 'MISS'].forEach((h, i) => {
        ctx.fillText(h, 24 + [0,140,280,360,400,450][i], y);
      });
      y += 5;
      ctx.fillStyle = '#334155';
      ctx.fillRect(20, y, W - 40, 1);
      y += 10;

      rows.forEach((a, idx) => {
        const bg = idx % 2 === 0 ? 'rgba(30,41,59,0.7)' : 'rgba(15,23,42,0.5)';
        ctx.fillStyle = bg;
        ctx.fillRect(20, y - 4, W - 40, rowH - 4);

        ctx.fillStyle = '#cbd5e1';
        ctx.font      = '11px Arial';
        ctx.fillText(a.date.slice(0, 18), 24, y + 14);
        ctx.fillText((a.labName || a.labId || '').substring(0, 17), 24 + 140, y + 14);
        ctx.fillStyle = '#94a3b8';
        ctx.font      = '10px Arial';
        ctx.fillText(a.entryType || '—', 24 + 280, y + 14);

        ctx.fillStyle = '#10b981'; ctx.font = 'bold 11px Arial';
        ctx.fillText(a.summary.well,    24 + 360, y + 14);
        ctx.fillStyle = '#f59e0b';
        ctx.fillText(a.summary.broken,  24 + 400, y + 14);
        ctx.fillStyle = '#ef4444';
        ctx.fillText(a.summary.missing, 24 + 450, y + 14);

        y += rowH;
      });

      y += 20;
      ctx.fillStyle = '#334155';
      ctx.fillRect(20, y, W - 40, 1);
      y += 16;
      ctx.fillStyle = '#475569';
      ctx.font      = '10px Arial';
      ctx.textAlign = 'center';
      ctx.fillText(`${LABS_DATA.config.orgName} Inventory System v${LABS_DATA.config.version}`, W / 2, y);

      const url = canvas.toDataURL('image/png');
      this._triggerDownload(url, `history_${username}_${new Date().toISOString().slice(0,10)}.png`);
      resolve();
    });
  },

  _triggerDownload: function (url, filename) {
    const a = document.createElement('a');
    a.href     = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }

};
